In [15]:
#用贝叶斯分类算法解决鸢尾花分类

import pandas as pd
import numpy as np
import random
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

X,y=datasets.load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
gnb=GaussianNB()
y_pred=gnb.fit(X_train,y_train).predict(X_test)
print("测试集数目为：%d 预测出错的数目为：%d "%(X_test.shape[0],(y_test!=y_pred).sum()))
print("分类的准确率为：%s"%(1-((y_test!=y_pred).sum()/X_test.shape[0])))







测试集数目为：30 预测出错的数目为：1 
分类的准确率为：0.9666666666666667


In [4]:
#利用鸢尾花数据来实现朴素贝叶斯分类

from sklearn import datasets

iris=datasets.load_iris()

print('数据的shape：',iris.data.shape)
print('数据的类型：',iris.data.dtype)
print('数据：',iris.data[:5])
print('数据标签的shape：',iris.target.shape)
print('数据的标签值：',iris.target[:5])

import pandas as pd

df=pd.DataFrame(iris.data,columns=feature_names)
df['label']=iris.target

import numpy as np
import matplotlib.pyplot as plt

data=np.array(df.iloc[:100,[2,3,-1]])#前100行；第3列到最后一列
X=data[:,:-1]
Y=data[:,-1]

class Model():
    def __init__(self,vec,X,Y):
        self.lamda=0
        self.vec=vec
        self.X=X
        self.Y=Y
    
    #均值
    def mean(self):
        res=[]
        n=len(self.X)
        for i in range(self.vec):
            sum=0
            for j in range(n):
                sum+=self.X[i,j]
            res.append(sum)
        return sum
    
    #方差
    def var(self):
        res=[]
        n=len(self.X)
        avg=mean(self.X)
        for i in range(self.vec):
            sum=0
            for j in range(n):
                sum+=(self.X[i,j]-avg[j])**2
            sum=sum**0.5/(n-1)
            res.append(sum)
        return res
    
    #核函数：标准化(高斯朴素贝叶斯：条件概率)
    def normalization(self):
        m=mean()
        v=var()
        res=[]
        for i in range(len(self.X)):
            tmp=[]
            for j in range(len(self.X[0])):
                exponent=math.exp(math.pow((self.X[i,j]-m),2)/-2*v)
                p=1/math.sqrt(2*math.pi*v)*exponent
                tmp.append(p)
            res.append(tmp)
        return res
    
    #先验概率
    def prior(self):
        priop_prob=[]
        Y=set(self.Y)
        K=len(Y)#分的类数
        K_dict=dict(zip(Y,np.zeros(len(self.Y),dtype=int)))
        for i in range(len(self.Y)):
            k_dict[self.Y[i]]+=1
        
        for i in range(len(Y)):
            priop_prob.append(k_dict[Y[i]]/len(self.Y))
                
        return priop_prob
    
    #条件概率
    def 
            
        

        
        
                

数据的shape： (150, 4)
数据的类型： float64
数据： [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
数据标签的shape： (150,)
数据的标签值： [0 0 0 0 0]


In [8]:
import numpy as np

p=1
x=np.array([1,2,3,4])
ip=np.exp(x-2.5)

print(ip)
for i in range(len(x)):
    p*=ip[i]
    #cla=p.index[np.argmax(p.values)]

print(p)

[0.22313016 0.60653066 1.64872127 4.48168907]
0.9999999999999999


In [142]:
import numpy as np
import pandas as pd
import random

dataSet=pd.read_csv('iris.csv',header=None)
dataSet.head()


#切分数据集
def randSpilt(dataSet,rate):
    l=list(dataSet.index)#提取索引
    random.shuffle(l)#打乱索引
    dataSet.index=l#将打乱后的索引重新复制给原始数据
    n=dataSet.shape[0]#总数据量
    m=int(n*rate)#训练集数量
    train=dataSet.loc[range(m),:]#前m行为训练集
    test=dataSet.loc[range(m,n),:]#后n-m行为测试集
    dataSet.index=range(dataSet.shape[0])#更新原数据集的索引
    test.index=range(test.shape[0])#更新测试集的索引
    return train,test

train,test=randSpilt(dataSet,0.8)

print(train.index)
print(test.index)
print(train.loc[:5,:])
print(type(train))

print(train.iloc[:,-1].value_counts())

#构建高斯朴素贝叶斯分类器
def gnb_classify(train,test):
    labels=train.iloc[:,-1].value_counts().index#提取标签种类
    mean=[]#存放每个类的均值
    std=[]#存放每个类的方差
    result=[]#存放测试集的预测结果
    
    """
    res=[]
    for i in labels:
        item=train.loc[train.iloc[:,-1]==i,:]
        
        for k in range(2):
            tmp=[]
            score=0
            for j in range(1,len(item)):
                score+=float(item.iloc[j,k])
            tmp.append(score)
        res.append(tmp)
    
    res=pd.DataFrame(res)
    print('!!!!!!!!!!!!!',res)
    """

    for i in labels:
        item=train.loc[train.iloc[:,-1]==i,:]#分别提取每一种类别
        m=item.iloc[1:,:-1].mean()#计算当前类别的均值
        s=np.sum((item.iloc[1:,:-1]-m)**2)/(item.shape[0])#计算当前类别的方差
        mean.append(m)
        std.append(s)
        
        #--------------!!!!!!!------------
        #print(m)
    means=pd.DataFrame(mean,index=labels)#变为DF式，索引为类标签
    stds=pd.DataFrame(std,index=labels)
    
    for j in range(test.shape[0]):
        iset=test.iloc[j,:-1].tolist()
        #print()
        
        iprob=np.exp(-1*(iset-means)**2/(2*stds))/(np.sqrt(2*np.pi*stds))#正态分布
        prob=1
        for k in range(test.shape[1]-1):#遍历每个特征
            prob*=iprob[k]
            cla=prob.index[np.argmax(prob.values)]#返回最大概率的类别
        result.append(cla)
    test['predict']=result
    acc=(test.iloc[:,-1]==test.iloc[:,-2]).mean()#计算预测准确率
    print(f'模型预测准确率为{acc}')
    return test
    


train,test=randSpilt(dataSet,0.8)
gnb_classify(train,test)
    

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
           dtype='int64')
RangeIndex(start=0, stop=21, step=1)
     0    1    2    3                4
0  6.8  3.2  5.9  2.3   Iris-virginica
1  6.9  3.1  5.1  2.3   Iris-virginica
2    7  3.2  4.7  1.4  Iris-versicolor
3  6.7  3.3  5.7  2.1   Iris-virginica
4  6.1  2.9  4.7  1.4  Iris-versicolor
5  6.9  3.1  4.9  1.5  Iris-versicolor
<class 'pandas.core.frame.DataFrame'>
Iris-versicolor    40
Iris-virginica     39
species             1
Name: 4, dtype: int64


C:\Users\mg\AppData\Local\Temp\ipykernel_62728\2167925674.py:57: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  m=item.iloc[1:,:-1].mean()#计算当前类别的均值


ZeroDivisionError: float division by zero

In [102]:
import pandas as pd

x=pd.DataFrame([[1,2,3,4],[5,6,7,8]])

print(x.iloc[:,:].mean(axis=1))

0    2.5
1    6.5
dtype: float64
